config/routes.rb
Rails.application.routes.draw do
  resources :members
  resources :tenants
  devise_for :users
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
  belongs_to :tenant
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  has_many :members
  has_many :users, through: :members
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :member, dependent: :destroy
  has_many :tenants, through: :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if current_user
      if session[:tenant_id]
        @tenant = session[:tenant_id]
      else
        @tenant = current_user.tenants.first
      end
      params[:tenant_id] = @tenant.id
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]

  # GET /tenants or /tenants.json
  def index
    @tenants = Tenant.all
  end

  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        @tenant.members.create(user: current_user, roles: { admin: true })
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tenant
    @tenant = Tenant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tenant_params
    params.require(:tenant).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/home/index.html.erb
<% if current_user %>
  <h3 class="pull-right">Organization: <%= @tenant.name %></h3>
<% else %>
  <div class="container-fluid p-5">
    <div class="mb-4 bg-light round-3">
      <div class="container-fluid py-5 text-center" id="jumbo-home">
        <h2>Welcome to the Project Management Application!</h2>
        <p class="lead">
          You'll love managing your project with our SaaS application. Please take a look at our great plans
        </p>
      </div>
    </div>
  </div>
  <div class="row justify-content-center pb-5">
    <div class="col-auto pe-5">
      <div class="card">
        <div class="card-header text-center">
          Free Plan
        </div>
        <div class="card-body text-left">
          <div class="features">
            <ul>
              <li>Unlimited file uploads</li>
              <li>Responsive design</li>
              <li>Access anywhere</li>
              <li>1 project</li>
            </ul>
            <hr>
            <div class="price text-center pb-3">
              Price: Free
            </div>
          </div>
          <div class="card-footer text-center pt-3">
            <%= link_to 'Sign Up', new_user_registration_path(plan: 'free'), class: 'btn btn-primary sign-up' %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-auto">
      <div class="card">
        <div class="card-header text-center">
          Premium Plan
        </div>
        <div class="card-body">
          <div class="features">
            <ul>
              <li>Unlimited file uploads</li>
              <li>Responsive design</li>
              <li>Access anywhere</li>
              <li class='extra'>Unlimited projects</li>
            </ul>
          </div>
          <hr>
          <div class="price text-center pb-3">
            Price: $20
          </div>
          <div class="card-footer text-center pt-3">
            <%= link_to 'Sign Up', new_user_registration_path(plan: 'premium'), class: 'btn btn-primary sign-up' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SAAS Project Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
      </ul>
    </div>
    <ul class="navbar-nav ms-auto">
      <% if current_user %>
        <li class="nav-item btn">
            <span class="badge">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe,
                            edit_user_registration_path, title: 'Edit Profile',
                            class: "text-decoration-none" %>
            </span>
        </li>
        <li class="nav-item pe-2">
          <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-danger" %>
        </li>
      <% else %>
        <li class="nav-item pe-2">
          <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary') %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasProjectApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div id="<%= dom_id tenant %>">
  <p>
    <strong>Name:</strong>
    <%= tenant.name %>
  </p>

</div>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Show this tenant", @tenant %> |
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tenants</h1>

<div id="tenants">
  <% @tenants.each do |tenant| %>
    <%= render tenant %>
    <p>
      <%= link_to "Show this tenant", tenant %>
    </p>
  <% end %>
</div>

<%= link_to "New tenant", new_tenant_path %>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tenant %>

<div>
  <%= link_to "Edit this tenant", edit_tenant_path(@tenant) %> |
  <%= link_to "Back to tenants", tenants_path %>

  <%= button_to "Destroy this tenant", @tenant, method: :delete %>
</div>